// <auto-generated />
using System;
using Hospital_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428071839_AddCalendarEvents")]
    partial class AddCalendarEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Management_System.Models.Appointment", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ArrivalConfirmation")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = "APT001",
                            AppointmentDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppointmentStatus = "Scheduled",
                            AppointmentTime = "09:00 AM",
                            ArrivalConfirmation = false,
                            CreationDate = new DateTime(2026, 4, 28, 8, 18, 38, 600, DateTimeKind.Local).AddTicks(8313),
                            DoctorId = "DOC001",
                            Notes = "Routine checkup",
                            PatientId = "PAT001"
                        },
                        new
                        {
                            AppointmentId = "APT002",
                            AppointmentDate = new DateTime(2027, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppointmentStatus = "Scheduled",
                            AppointmentTime = "11:00 AM",
                            ArrivalConfirmation = false,
                            CreationDate = new DateTime(2026, 4, 28, 8, 18, 38, 600, DateTimeKind.Local).AddTicks(8358),
                            DoctorId = "DOC001",
                            Notes = "Follow-up",
                            PatientId = "PAT002"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.CalendarEvent", b =>
                {
                    b.Property<string>("CalendarEventId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CalendarEventId");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssignedStaffId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Room")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DeviceId");

                    b.HasIndex("AssignedStaffId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            DeviceId = "DEV001",
                            AssignedStaffId = "DOC001",
                            DeviceName = "Dell Latitude 7420",
                            DeviceType = "Laptop",
                            LastUpdated = new DateTime(2026, 4, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "In Use"
                        },
                        new
                        {
                            DeviceId = "DEV002",
                            AssignedStaffId = "NUR001",
                            DeviceName = "HP EliteBook 840",
                            DeviceType = "Laptop",
                            LastUpdated = new DateTime(2026, 4, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "In Use"
                        },
                        new
                        {
                            DeviceId = "DEV003",
                            DeviceName = "iPad Pro 12.9",
                            DeviceType = "Tablet",
                            LastUpdated = new DateTime(2026, 4, 21, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Room = "Ward A - Room 1",
                            Status = "In Use"
                        },
                        new
                        {
                            DeviceId = "DEV004",
                            DeviceName = "iPad Mini",
                            DeviceType = "Tablet",
                            LastUpdated = new DateTime(2026, 4, 21, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Room = "Ward B - Room 3",
                            Status = "Available"
                        },
                        new
                        {
                            DeviceId = "DEV005",
                            DeviceName = "Lenovo ThinkPad X1",
                            DeviceType = "Laptop",
                            LastUpdated = new DateTime(2026, 4, 22, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Available"
                        },
                        new
                        {
                            DeviceId = "DEV006",
                            DeviceName = "Patient Vitals Monitor",
                            DeviceType = "Medical Device",
                            LastUpdated = new DateTime(2026, 4, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Room = "ICU - Bed 2",
                            Status = "In Use"
                        },
                        new
                        {
                            DeviceId = "DEV007",
                            DeviceName = "Samsung Tablet S8",
                            DeviceType = "Tablet",
                            LastUpdated = new DateTime(2026, 4, 23, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Room = "Ward A - Room 2",
                            Status = "Faulty"
                        },
                        new
                        {
                            DeviceId = "DEV008",
                            DeviceName = "Barcode Scanner ZX-300",
                            DeviceType = "Scanner",
                            LastUpdated = new DateTime(2026, 4, 23, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            Room = "Pharmacy",
                            Status = "Available"
                        },
                        new
                        {
                            DeviceId = "DEV009",
                            AssignedStaffId = "ITP001",
                            DeviceName = "MacBook Air M2",
                            DeviceType = "Laptop",
                            LastUpdated = new DateTime(2026, 4, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "In Use"
                        },
                        new
                        {
                            DeviceId = "DEV010",
                            AssignedStaffId = "DOC002",
                            DeviceName = "Surface Pro 9",
                            DeviceType = "Tablet/Laptop",
                            LastUpdated = new DateTime(2026, 4, 24, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            Status = "Faulty"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Diagnosis", b =>
                {
                    b.Property<string>("DiagnosisId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiagnosisName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("VisitId");

                    b.ToTable("Diagnoses");

                    b.HasData(
                        new
                        {
                            DiagnosisId = "DIA001",
                            Description = "Patient advised to monitor blood pressure and reduce salt intake.",
                            DiagnosisDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiagnosisName = "Mild Hypertension",
                            VisitId = "VIS001"
                        },
                        new
                        {
                            DiagnosisId = "DIA002",
                            Description = "Symptoms consistent with seasonal allergic rhinitis.",
                            DiagnosisDate = new DateTime(2027, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiagnosisName = "Seasonal Allergies",
                            VisitId = "VIS002"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.LabTestResult", b =>
                {
                    b.Property<string>("TestId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LabTechId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResultDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("TestId");

                    b.HasIndex("LabTechId");

                    b.HasIndex("VisitId");

                    b.ToTable("LabTestResults");

                    b.HasData(
                        new
                        {
                            TestId = "LAB001",
                            LabTechId = "LBT001",
                            ResultDate = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResultDetails = "Blood pressure markers reviewed. No urgent abnormality detected.",
                            Status = "Completed",
                            TestType = "Blood Test",
                            UploadDate = new DateTime(2026, 9, 19, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitId = "VIS001"
                        },
                        new
                        {
                            TestId = "LAB002",
                            LabTechId = "LBT001",
                            ResultDate = new DateTime(2027, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResultDetails = "Draft result pending final review before doctor access.",
                            Status = "Pending",
                            TestType = "Allergy Panel",
                            UploadDate = new DateTime(2027, 4, 19, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            VisitId = "VIS002"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiverType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssignedDoctorId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PatientDateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientEmergencyContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientEmergencyContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientOtherNames")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PatientId");

                    b.HasIndex("AssignedDoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = "PAT001",
                            AssignedDoctorId = "DOC001",
                            CreationDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientAddress = "123 Main Street, London",
                            PatientDateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientEmail = "Johndabomb@yahoo.com",
                            PatientEmergencyContactName = "Jane Doe",
                            PatientEmergencyContactPhoneNumber = "07987654321",
                            PatientFirstName = "John",
                            PatientLastName = "Doe",
                            PatientOtherNames = "Michael",
                            PatientPhoneNumber = "07123456789"
                        },
                        new
                        {
                            PatientId = "PAT002",
                            AssignedDoctorId = "DOC002",
                            CreationDate = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientAddress = "456 Elm Street, London",
                            PatientDateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientEmail = "MilleSmith3@gmail.com",
                            PatientEmergencyContactName = "Emily Smith",
                            PatientEmergencyContactPhoneNumber = "07123456789",
                            PatientFirstName = "Millie",
                            PatientLastName = "Smith",
                            PatientPhoneNumber = "07987654321"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Prescription", b =>
                {
                    b.Property<string>("PrescriptionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PharmacistId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrescriptionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("PharmacistId");

                    b.HasIndex("VisitId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionId = "PRE001",
                            Notes = "Review needed in 2 weeks.",
                            PharmacistId = "PHA001",
                            PrescriptionText = "Boscopan 5mg once daily",
                            Status = "Pending",
                            VisitId = "VIS001"
                        },
                        new
                        {
                            PrescriptionId = "PRE002",
                            Notes = "Take as needed during allergy season.",
                            PharmacistId = "PHA001",
                            PrescriptionText = "Cetirizine 10mg once daily",
                            Status = "Pending",
                            VisitId = "VIS002"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActiveStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StaffDateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StaffEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffEmergencyContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffEmergencyContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffFirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffLastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffOtherNames")
                        .HasColumnType("longtext");

                    b.Property<string>("StaffPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffId = "DOC001",
                            ActiveStatus = "Active",
                            StaffAddress = "1 Hospital Way, London",
                            StaffDateOfBirth = new DateTime(1985, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "amelia.hart@gmail.com",
                            StaffEmergencyContactName = "John Hart",
                            StaffEmergencyContactPhoneNumber = "07987654321",
                            StaffFirstName = "Amelia",
                            StaffLastName = "Hart",
                            StaffOtherNames = "Gracie",
                            StaffPhoneNumber = "07123456789",
                            StaffRole = "Doctor",
                            StartDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "DOC002",
                            ActiveStatus = "Active",
                            StaffAddress = "12 Westminster street, London",
                            StaffDateOfBirth = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "JamesAdeoye@hms.co.uk",
                            StaffEmergencyContactName = "Adeola Bankole",
                            StaffEmergencyContactPhoneNumber = "00182936673",
                            StaffFirstName = "James",
                            StaffLastName = "Adeoye",
                            StaffPhoneNumber = "07853295100",
                            StaffRole = "Doctor",
                            StartDate = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "NUR001",
                            ActiveStatus = "Active",
                            StaffAddress = "12 Lockerbie road, London",
                            StaffDateOfBirth = new DateTime(1965, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "AmandaChigozeE@gmail.com",
                            StaffEmergencyContactName = "Amarachi Anyagu",
                            StaffEmergencyContactPhoneNumber = "07911282556",
                            StaffFirstName = "Amanda",
                            StaffLastName = "Chigoze",
                            StaffOtherNames = "Eberechukwu",
                            StaffPhoneNumber = "07911873421",
                            StaffRole = "Nurse",
                            StartDate = new DateTime(2000, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "LBT001",
                            ActiveStatus = "Active",
                            StaffAddress = "34 The Maltings, London",
                            StaffDateOfBirth = new DateTime(1990, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "JacobBradford@yahoo.com",
                            StaffEmergencyContactName = "Jackson Bradford",
                            StaffEmergencyContactPhoneNumber = "03569829334",
                            StaffFirstName = "Jacob",
                            StaffLastName = "Bradford",
                            StaffOtherNames = "Ezekiel",
                            StaffPhoneNumber = "09567345128",
                            StaffRole = "Lab Technician",
                            StartDate = new DateTime(2015, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "REP001",
                            ActiveStatus = "Active",
                            StaffAddress = "56 High Street, London",
                            StaffDateOfBirth = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "EmilySmith@hms.co.uk",
                            StaffEmergencyContactName = "Sarah Smith",
                            StaffEmergencyContactPhoneNumber = "07987654321",
                            StaffFirstName = "Emily",
                            StaffLastName = "Smith",
                            StaffOtherNames = "Rose",
                            StaffPhoneNumber = "07451239876",
                            StaffRole = "Receptionist",
                            StartDate = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "SMA001",
                            ActiveStatus = "Active",
                            StaffAddress = "78 Park Avenue, London",
                            StaffDateOfBirth = new DateTime(1980, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "JohnsonJonson13@hsm.co.uk",
                            StaffEmergencyContactName = "Laura Johnson",
                            StaffEmergencyContactPhoneNumber = "07912345678",
                            StaffFirstName = "Michael",
                            StaffLastName = "Johnson",
                            StaffPhoneNumber = "07345678901",
                            StaffRole = "System Administrator",
                            StartDate = new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "PHA001",
                            ActiveStatus = "Active",
                            StaffAddress = "90 Elm Street, London",
                            StaffDateOfBirth = new DateTime(1985, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "GraceWilliams@hsm.co.uk",
                            StaffEmergencyContactName = "Sophia Williams",
                            StaffEmergencyContactPhoneNumber = "07987654321",
                            StaffFirstName = "Olivia",
                            StaffLastName = "Williams",
                            StaffOtherNames = "Grace",
                            StaffPhoneNumber = "07654321098",
                            StaffRole = "Pharmacist",
                            StartDate = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "ITP001",
                            ActiveStatus = "Active",
                            StaffAddress = "123 Tech Lane, London",
                            StaffDateOfBirth = new DateTime(1992, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "DavidITWhiz@hsm.co.uk",
                            StaffEmergencyContactName = "James Brown",
                            StaffEmergencyContactPhoneNumber = "07987654321",
                            StaffFirstName = "David",
                            StaffLastName = "Brown",
                            StaffOtherNames = "Alexander",
                            StaffPhoneNumber = "07123456789",
                            StaffRole = "IT Personnel",
                            StartDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedToId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.UserAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PasswordLastChanged")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AccountId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountStatus = "Active",
                            Email = "Millie Smith",
                            LastLogin = new DateTime(2026, 2, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "#90ndjj3",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = "PAT002",
                            Role = "Patient"
                        },
                        new
                        {
                            AccountId = 2,
                            AccountStatus = "Active",
                            Email = "GraceWilliams@hsm.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 8, 10, 12, 0, DateTimeKind.Unspecified),
                            Password = "Gracie2456",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Pharmacist",
                            StaffId = "PHA001"
                        },
                        new
                        {
                            AccountId = 3,
                            AccountStatus = "Active",
                            Email = "EmilySmith@hms.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 9, 15, 30, 0, DateTimeKind.Unspecified),
                            Password = "Emily2021",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Receptionist",
                            StaffId = "REP001"
                        },
                        new
                        {
                            AccountId = 4,
                            AccountStatus = "Active",
                            Email = "Johndabomb@yahoo.com",
                            LastLogin = new DateTime(2025, 2, 5, 10, 20, 45, 0, DateTimeKind.Unspecified),
                            Password = "LawandOrdersvu",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = "PAT001",
                            Role = "Patient"
                        },
                        new
                        {
                            AccountId = 5,
                            AccountStatus = "Active",
                            Email = "amelia.hart@gmail.com",
                            LastLogin = new DateTime(2026, 2, 5, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Password = "nAkEdInMaNhAtTaN",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Doctor",
                            StaffId = "DOC001"
                        },
                        new
                        {
                            AccountId = 6,
                            AccountStatus = "Active",
                            Email = "JamesAdeoye@hms.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 12, 45, 15, 0, DateTimeKind.Unspecified),
                            Password = "2026hmsyay",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Doctor",
                            StaffId = "DOC002"
                        },
                        new
                        {
                            AccountId = 7,
                            AccountStatus = "Active",
                            Email = "AmandaChigozeE@gmail.com",
                            LastLogin = new DateTime(2026, 2, 5, 13, 50, 30, 0, DateTimeKind.Unspecified),
                            Password = "NurseAmanda2026",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Nurse",
                            StaffId = "NUR001"
                        },
                        new
                        {
                            AccountId = 8,
                            AccountStatus = "Active",
                            Email = "JacobBradford@yahoo.com",
                            LastLogin = new DateTime(2026, 2, 5, 14, 55, 45, 0, DateTimeKind.Unspecified),
                            Password = "AbbottonAbbottonAbbott",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Lab Technician",
                            StaffId = "LBT001"
                        },
                        new
                        {
                            AccountId = 9,
                            AccountStatus = "Active",
                            Email = "JohnsonJonson13@hsm.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "LuckyJohnson",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "System Administrator",
                            StaffId = "SMA001"
                        },
                        new
                        {
                            AccountId = 10,
                            AccountStatus = "Active",
                            Email = "DavidITWhiz@hsm.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 16, 10, 15, 0, DateTimeKind.Unspecified),
                            Password = "+lol^^cantguessmypassword",
                            PasswordLastChanged = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "IT Personnel",
                            StaffId = "ITP001"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Visit", b =>
                {
                    b.Property<string>("VisitId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("VisitId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            VisitId = "VIS001",
                            AppointmentId = "APT001",
                            DoctorId = "DOC001",
                            Notes = "Initial consultation after patient arrival.",
                            PatientId = "PAT001",
                            VisitDateTime = new DateTime(2026, 9, 18, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            VisitId = "VIS002",
                            AppointmentId = "APT002",
                            DoctorId = "DOC001",
                            Notes = "Follow-up consultation.",
                            PatientId = "PAT002",
                            VisitDateTime = new DateTime(2027, 4, 18, 11, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Vitals", b =>
                {
                    b.Property<string>("VitalsId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeartRate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NurseId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RespiratoryRate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("VitalsId");

                    b.HasIndex("NurseId");

                    b.HasIndex("VisitId");

                    b.ToTable("Vitals");

                    b.HasData(
                        new
                        {
                            VitalsId = "VIT001",
                            BloodPressure = "140/90",
                            HeartRate = "82 bpm",
                            IsDraft = false,
                            Notes = "Patient stable but blood pressure slightly elevated.",
                            NurseId = "NUR001",
                            RecordedAt = new DateTime(2026, 9, 18, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            RespiratoryRate = "18 breaths/min",
                            Temperature = 37,
                            VisitId = "VIS001"
                        },
                        new
                        {
                            VitalsId = "VIT002",
                            BloodPressure = "118/76",
                            HeartRate = "74 bpm",
                            IsDraft = true,
                            Notes = "Vitals within normal range.",
                            NurseId = "NUR001",
                            RecordedAt = new DateTime(2027, 4, 18, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            RespiratoryRate = "16 breaths/min",
                            Temperature = 36,
                            VisitId = "VIS002"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Appointment", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Device", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffId");

                    b.Navigation("AssignedStaff");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Diagnosis", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.LabTestResult", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "LabTech")
                        .WithMany()
                        .HasForeignKey("LabTechId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTech");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Patient", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "AssignedDoctor")
                        .WithMany("Patients")
                        .HasForeignKey("AssignedDoctorId");

                    b.Navigation("AssignedDoctor");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Prescription", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacist");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Ticket", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.Navigation("AssignedTo");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.UserAccount", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.HasOne("Hospital_Management_System.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Visit", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Staff", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Vitals", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "Nurse")
                        .WithMany()
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Staff", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
