// <auto-generated />
using System;
using Hospital_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417113425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Management_System.Models.Appointment", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ArrivalConfirmation")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = "APT001",
                            AppointmentDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppointmentStatus = "Scheduled",
                            AppointmentTime = "09:00 AM",
                            ArrivalConfirmation = false,
                            CreationDate = new DateTime(2026, 4, 17, 12, 34, 24, 513, DateTimeKind.Local).AddTicks(3468),
                            DoctorId = "DOC001",
                            Notes = "Routine checkup",
                            PatientId = "PAT001"
                        },
                        new
                        {
                            AppointmentId = "APT002",
                            AppointmentDate = new DateTime(2027, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AppointmentStatus = "Scheduled",
                            AppointmentTime = "11:00 AM",
                            ArrivalConfirmation = false,
                            CreationDate = new DateTime(2026, 4, 17, 12, 34, 24, 513, DateTimeKind.Local).AddTicks(3518),
                            DoctorId = "DOC001",
                            Notes = "Follow-up",
                            PatientId = "PAT002"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Diagnosis", b =>
                {
                    b.Property<string>("DiagnosisId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiagnosisName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("VisitId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.LabTestResult", b =>
                {
                    b.Property<string>("TestId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LabTechId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("TestId");

                    b.HasIndex("LabTechId");

                    b.HasIndex("VisitId");

                    b.ToTable("LabTestResults");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssignedDoctorId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PatientDateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientEmergencyContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientEmergencyContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientOtherNames")
                        .HasColumnType("longtext");

                    b.Property<string>("PatientPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PatientId");

                    b.HasIndex("AssignedDoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = "PAT001",
                            AssignedDoctorId = "DOC001",
                            CreationDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientAddress = "123 Main Street, London",
                            PatientDateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientEmail = "Johndabomb@yahoo.com",
                            PatientEmergencyContactName = "Jane Doe",
                            PatientEmergencyContactPhoneNumber = "07987654321",
                            PatientFirstName = "John",
                            PatientLastName = "Doe",
                            PatientOtherNames = "Michael",
                            PatientPhoneNumber = "07123456789"
                        },
                        new
                        {
                            PatientId = "PAT002",
                            AssignedDoctorId = "DOC002",
                            CreationDate = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientAddress = "456 Elm Street, London",
                            PatientDateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientEmail = "MilleSmith3@gmail.com",
                            PatientEmergencyContactName = "Emily Smith",
                            PatientEmergencyContactPhoneNumber = "07123456789",
                            PatientFirstName = "Millie",
                            PatientLastName = "Smith",
                            PatientPhoneNumber = "07987654321"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Prescription", b =>
                {
                    b.Property<string>("PrescriptionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PharmacistId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrescriptionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("PharmacistId");

                    b.HasIndex("VisitId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActiveStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StaffDateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StaffEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffEmergencyContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffEmergencyContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffFirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffLastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffOtherNames")
                        .HasColumnType("longtext");

                    b.Property<string>("StaffPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffId = "DOC001",
                            ActiveStatus = "Active",
                            StaffAddress = "1 Hospital Way, London",
                            StaffDateOfBirth = new DateTime(1985, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "amelia.hart@gmail.com",
                            StaffEmergencyContactName = "John Hart",
                            StaffEmergencyContactPhoneNumber = "07987654321",
                            StaffFirstName = "Amelia",
                            StaffLastName = "Hart",
                            StaffOtherNames = "Gracie",
                            StaffPhoneNumber = "07123456789",
                            StaffRole = "Doctor",
                            StartDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "DOC002",
                            ActiveStatus = "Active",
                            StaffAddress = "12 Westminster street, London",
                            StaffDateOfBirth = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "JamesAdeoye@hms.co.uk",
                            StaffEmergencyContactName = "Adeola Bankole",
                            StaffEmergencyContactPhoneNumber = "00182936673",
                            StaffFirstName = "James",
                            StaffLastName = "Adeoye",
                            StaffPhoneNumber = "07853295100",
                            StaffRole = "Doctor",
                            StartDate = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "NUR001",
                            ActiveStatus = "Active",
                            StaffAddress = "12 Lockerbie road, London",
                            StaffDateOfBirth = new DateTime(1965, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "AmandaChigozeE@gmail.com",
                            StaffEmergencyContactName = "Amarachi Anyagu",
                            StaffEmergencyContactPhoneNumber = "07911282556",
                            StaffFirstName = "Amanda",
                            StaffLastName = "Chigoze",
                            StaffOtherNames = "Eberechukwu",
                            StaffPhoneNumber = "07911873421",
                            StaffRole = "Nurse",
                            StartDate = new DateTime(2000, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "LBT001",
                            ActiveStatus = "Active",
                            StaffAddress = "34 The Maltings, London",
                            StaffDateOfBirth = new DateTime(1990, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "JacobBradford@yahoo.com",
                            StaffEmergencyContactName = "Jackson Bradford",
                            StaffEmergencyContactPhoneNumber = "03569829334",
                            StaffFirstName = "Jacob",
                            StaffLastName = "Bradford",
                            StaffOtherNames = "Ezekiel",
                            StaffPhoneNumber = "09567345128",
                            StaffRole = "Lab Technician",
                            StartDate = new DateTime(2015, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "REP001",
                            ActiveStatus = "Active",
                            StaffAddress = "56 High Street, London",
                            StaffDateOfBirth = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "EmilySmith@hms.co.uk",
                            StaffEmergencyContactName = "Sarah Smith",
                            StaffEmergencyContactPhoneNumber = "07987654321",
                            StaffFirstName = "Emily",
                            StaffLastName = "Smith",
                            StaffOtherNames = "Rose",
                            StaffPhoneNumber = "07451239876",
                            StaffRole = "Receptionist",
                            StartDate = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "SMA001",
                            ActiveStatus = "Active",
                            StaffAddress = "78 Park Avenue, London",
                            StaffDateOfBirth = new DateTime(1980, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "JohnsonJonson13@hsm.co.uk",
                            StaffEmergencyContactName = "Laura Johnson",
                            StaffEmergencyContactPhoneNumber = "07912345678",
                            StaffFirstName = "Michael",
                            StaffLastName = "Johnson",
                            StaffPhoneNumber = "07345678901",
                            StaffRole = "System Administrator",
                            StartDate = new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "PHA001",
                            ActiveStatus = "Active",
                            StaffAddress = "90 Elm Street, London",
                            StaffDateOfBirth = new DateTime(1985, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "GraceWilliams@hsm.co.uk",
                            StaffEmergencyContactName = "Sophia Williams",
                            StaffEmergencyContactPhoneNumber = "07987654321",
                            StaffFirstName = "Olivia",
                            StaffLastName = "Williams",
                            StaffOtherNames = "Grace",
                            StaffPhoneNumber = "07654321098",
                            StaffRole = "Pharmacist",
                            StartDate = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StaffId = "ITP001",
                            ActiveStatus = "Active",
                            StaffAddress = "123 Tech Lane, London",
                            StaffDateOfBirth = new DateTime(1992, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffEmail = "DavidITWhiz@hsm.co.uk",
                            StaffEmergencyContactName = "James Brown",
                            StaffEmergencyContactPhoneNumber = "07987654321",
                            StaffFirstName = "David",
                            StaffLastName = "Brown",
                            StaffOtherNames = "Alexander",
                            StaffPhoneNumber = "07123456789",
                            StaffRole = "IT Personnel",
                            StartDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.UserAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AccountId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountStatus = "Active",
                            Email = "Millie Smith",
                            LastLogin = new DateTime(2026, 2, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "#90ndjj3",
                            PatientId = "PAT002",
                            Role = "Patient"
                        },
                        new
                        {
                            AccountId = 2,
                            AccountStatus = "Active",
                            Email = "GraceWilliams@hsm.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 8, 10, 12, 0, DateTimeKind.Unspecified),
                            Password = "Gracie2456",
                            Role = "Pharmacist",
                            StaffId = "PHA001"
                        },
                        new
                        {
                            AccountId = 3,
                            AccountStatus = "Active",
                            Email = "EmilySmith@hms.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 9, 15, 30, 0, DateTimeKind.Unspecified),
                            Password = "Emily2021",
                            Role = "Receptionist",
                            StaffId = "REP001"
                        },
                        new
                        {
                            AccountId = 4,
                            AccountStatus = "Active",
                            Email = "Johndabomb@yahoo.com",
                            LastLogin = new DateTime(2025, 2, 5, 10, 20, 45, 0, DateTimeKind.Unspecified),
                            Password = "LawandOrdersvu",
                            PatientId = "PAT001",
                            Role = "Patient"
                        },
                        new
                        {
                            AccountId = 5,
                            AccountStatus = "Active",
                            Email = "amelia.hart@gmail.com",
                            LastLogin = new DateTime(2026, 2, 5, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Password = "nAkEdInMaNhAtTaN",
                            Role = "Doctor",
                            StaffId = "DOC001"
                        },
                        new
                        {
                            AccountId = 6,
                            AccountStatus = "Active",
                            Email = "JamesAdeoye@hms.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 12, 45, 15, 0, DateTimeKind.Unspecified),
                            Password = "2026hmsyay",
                            Role = "Doctor",
                            StaffId = "DOC002"
                        },
                        new
                        {
                            AccountId = 7,
                            AccountStatus = "Active",
                            Email = "AmandaChigozeE@gmail.com",
                            LastLogin = new DateTime(2026, 2, 5, 13, 50, 30, 0, DateTimeKind.Unspecified),
                            Password = "NurseAmanda2026",
                            Role = "Nurse",
                            StaffId = "NUR001"
                        },
                        new
                        {
                            AccountId = 8,
                            AccountStatus = "Active",
                            Email = "JacobBradford@yahoo.com",
                            LastLogin = new DateTime(2026, 2, 5, 14, 55, 45, 0, DateTimeKind.Unspecified),
                            Password = "AbbottonAbbottonAbbott",
                            Role = "Lab Technician",
                            StaffId = "LBT001"
                        },
                        new
                        {
                            AccountId = 9,
                            AccountStatus = "Active",
                            Email = "JohnsonJonson13@hsm.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "LuckyJohnson",
                            Role = "System Administrator",
                            StaffId = "SMA001"
                        },
                        new
                        {
                            AccountId = 10,
                            AccountStatus = "Active",
                            Email = "DavidITWhiz@hsm.co.uk",
                            LastLogin = new DateTime(2026, 2, 5, 16, 10, 15, 0, DateTimeKind.Unspecified),
                            Password = "+lol^^cantguessmypassword",
                            Role = "IT Personnel",
                            StaffId = "ITP001"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Visit", b =>
                {
                    b.Property<string>("VisitId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("VisitId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Vitals", b =>
                {
                    b.Property<string>("VitalsId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeartRate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NurseId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RespiratoryRate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<string>("VisitId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("VitalsId");

                    b.HasIndex("NurseId");

                    b.HasIndex("VisitId");

                    b.ToTable("Vitals");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Appointment", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Diagnosis", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.LabTestResult", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "LabTech")
                        .WithMany()
                        .HasForeignKey("LabTechId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTech");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Patient", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "AssignedDoctor")
                        .WithMany("Patients")
                        .HasForeignKey("AssignedDoctorId");

                    b.Navigation("AssignedDoctor");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Prescription", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacist");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.UserAccount", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.HasOne("Hospital_Management_System.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Visit", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Staff", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Vitals", b =>
                {
                    b.HasOne("Hospital_Management_System.Models.Staff", "Nurse")
                        .WithMany()
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Models.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nurse");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital_Management_System.Models.Staff", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
